# Generated by Django 2.1.7 on 2019-03-12 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RDFClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdf_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RDFProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdf_property', models.CharField(max_length=50)),
                ('inverse_rdf_property', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RDFSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=20)),
                ('uri', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='rdfproperty',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkeddata.RDFSchema'),
        ),
        migrations.AddField(
            model_name='rdfclass',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkeddata.RDFSchema'),
        ),
    ]
