# Generated by Django 2.1.7 on 2019-03-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_type', models.CharField(choices=[('instance', 'instance'), ('interval', 'interval')], max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_date_month', models.BooleanField(default=False)),
                ('start_date_day', models.BooleanField(default=False)),
                ('latest_start_date', models.DateField(blank=True, null=True)),
                ('latest_start_date_month', models.BooleanField(default=False)),
                ('latest_start_date_day', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_date_month', models.BooleanField(default=False)),
                ('end_date_day', models.BooleanField(default=False)),
                ('earliest_end_date', models.DateField(blank=True, null=True)),
                ('earliest_end_date_month', models.BooleanField(default=False)),
                ('earliest_end_date_day', models.BooleanField(default=False)),
            ],
        ),
    ]
