# Generated by Django 2.1.7 on 2019-03-12 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkeddata', '0001_initial'),
        ('events', '0001_initial'),
        ('objects', '__first__'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('inscription', models.TextField(blank=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemorialAssociatedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MemorialAssociatedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MemorialAssociatedOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MemorialAssociatedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MemorialAssociatedPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MemorialAssociatedSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MemorialAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('rdf_property', models.ManyToManyField(blank=True, to='linkeddata.RDFProperty')),
            ],
        ),
        migrations.CreateModel(
            name='MemorialImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='memorials')),
                ('caption', models.TextField(blank=True)),
                ('credit', models.CharField(max_length=250)),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorials.Memorial')),
            ],
        ),
        migrations.CreateModel(
            name='MemorialName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('inscription', models.TextField(blank=True)),
                ('row', models.IntegerField(blank=True, null=True)),
                ('column', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorials.Memorial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemorialPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('inscription', models.TextField(blank=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorials.Memorial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemorialPlaceAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('rdf_property', models.ManyToManyField(blank=True, to='linkeddata.RDFProperty')),
            ],
        ),
        migrations.CreateModel(
            name='MemorialSourceAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('rdf_property', models.ManyToManyField(blank=True, to='linkeddata.RDFProperty')),
            ],
        ),
        migrations.AddField(
            model_name='memorialname',
            name='memorial_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memorials.MemorialPart'),
        ),
        migrations.AddField(
            model_name='memorialname',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
        migrations.AddField(
            model_name='memorialassociatedsource',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorials.MemorialSourceAssociation'),
        ),
        migrations.AddField(
            model_name='memorialassociatedsource',
            name='memorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorials.Memorial'),
        ),
        migrations.AddField(
            model_name='memorialassociatedsource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Source'),
        ),
        migrations.AddField(
            model_name='memorialassociatedplace',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorials.MemorialPlaceAssociation'),
        ),
        migrations.AddField(
            model_name='memorialassociatedplace',
            name='memorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorials.Memorial'),
        ),
        migrations.AddField(
            model_name='memorialassociatedplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
        migrations.AddField(
            model_name='memorialassociatedperson',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorials.MemorialAssociation'),
        ),
        migrations.AddField(
            model_name='memorialassociatedperson',
            name='memorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorials.Memorial'),
        ),
        migrations.AddField(
            model_name='memorialassociatedperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
        migrations.AddField(
            model_name='memorialassociatedorganisation',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorials.MemorialAssociation'),
        ),
        migrations.AddField(
            model_name='memorialassociatedorganisation',
            name='memorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorials.Memorial'),
        ),
        migrations.AddField(
            model_name='memorialassociatedorganisation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Organisation'),
        ),
        migrations.AddField(
            model_name='memorialassociatedobject',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorials.MemorialAssociation'),
        ),
        migrations.AddField(
            model_name='memorialassociatedobject',
            name='memorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorials.Memorial'),
        ),
        migrations.AddField(
            model_name='memorialassociatedobject',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.Object'),
        ),
        migrations.AddField(
            model_name='memorialassociatedevent',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorials.MemorialAssociation'),
        ),
        migrations.AddField(
            model_name='memorialassociatedevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='memorialassociatedevent',
            name='memorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorials.Memorial'),
        ),
        migrations.AddField(
            model_name='memorial',
            name='associated_events',
            field=models.ManyToManyField(through='memorials.MemorialAssociatedEvent', to='events.Event'),
        ),
        migrations.AddField(
            model_name='memorial',
            name='associated_objects',
            field=models.ManyToManyField(through='memorials.MemorialAssociatedObject', to='objects.Object'),
        ),
        migrations.AddField(
            model_name='memorial',
            name='associated_organisations',
            field=models.ManyToManyField(through='memorials.MemorialAssociatedOrganisation', to='people.Organisation'),
        ),
        migrations.AddField(
            model_name='memorial',
            name='associated_people',
            field=models.ManyToManyField(through='memorials.MemorialAssociatedPerson', to='people.Person'),
        ),
        migrations.AddField(
            model_name='memorial',
            name='associated_places',
            field=models.ManyToManyField(through='memorials.MemorialAssociatedPlace', to='places.Place'),
        ),
        migrations.AddField(
            model_name='memorial',
            name='associated_sources',
            field=models.ManyToManyField(through='memorials.MemorialAssociatedSource', to='sources.Source'),
        ),
        migrations.AddField(
            model_name='memorial',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memorial_location', to='places.Place'),
        ),
    ]
