# Generated by Django 2.1.7 on 2019-03-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativepersonname',
            name='memorials',
            field=models.ManyToManyField(blank=True, to='memorials.Memorial'),
        ),
        migrations.AddField(
            model_name='death',
            name='memorials',
            field=models.ManyToManyField(blank=True, null=True, to='memorials.Memorial'),
        ),
        migrations.AddField(
            model_name='lifeevent',
            name='memorials',
            field=models.ManyToManyField(blank=True, null=True, to='memorials.Memorial'),
        ),
        migrations.AddField(
            model_name='personassociatedorganisation',
            name='memorials',
            field=models.ManyToManyField(blank=True, null=True, to='memorials.Memorial'),
        ),
        migrations.AddField(
            model_name='rank',
            name='memorials',
            field=models.ManyToManyField(blank=True, null=True, to='memorials.Memorial'),
        ),
    ]
