# Generated by Django 2.1.7 on 2019-03-12 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkeddata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_place', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('publication_date_month_known', models.BooleanField(default=False)),
                ('publication_date_day_known', models.BooleanField(default=False)),
                ('publication_date_end', models.DateField(blank=True, null=True)),
                ('publication_date_end_month_known', models.BooleanField(default=False)),
                ('publication_date_end_day_known', models.BooleanField(default=False)),
                ('collection_title', models.CharField(blank=True, max_length=250, null=True)),
                ('collection_item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('repository_item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('citation', models.CharField(blank=True, max_length=250, null=True)),
                ('pages', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('rdf_url', models.URLField(blank=True, null=True)),
                ('json_url', models.URLField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_source', to='sources.Source')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SourceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Source')),
            ],
        ),
        migrations.CreateModel(
            name='SourcePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SourceRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('inverse_label', models.CharField(blank=True, max_length=50, null=True)),
                ('rdf_property', models.ManyToManyField(blank=True, to='linkeddata.RDFProperty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('rdf_class', models.ManyToManyField(blank=True, to='linkeddata.RDFClass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('start_earliest_date', models.DateField(blank=True, null=True)),
                ('start_earliest_month', models.BooleanField(default=False)),
                ('start_earliest_day', models.BooleanField(default=False)),
                ('end_earliest_date', models.DateField(blank=True, null=True)),
                ('end_earliest_month', models.BooleanField(default=False)),
                ('end_earliest_day', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('credit', models.TextField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sources', models.ManyToManyField(blank=True, null=True, to='sources.Source')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='sourceperson',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.SourceRole'),
        ),
        migrations.AddField(
            model_name='sourceperson',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Source'),
        ),
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.SourceType'),
        ),
    ]
