# Generated by Django 2.1.7 on 2019-03-12 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='creators',
            field=models.ManyToManyField(blank=True, null=True, through='sources.SourcePerson', to='people.Person'),
        ),
        migrations.AddField(
            model_name='source',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Repository'),
        ),
        migrations.AddField(
            model_name='sourceperson',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
