# Generated by Django 2.1.7 on 2019-03-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_auto_20190311_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='creators',
            field=models.ManyToManyField(blank=True, through='sources.SourcePerson', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='story',
            name='sources',
            field=models.ManyToManyField(blank=True, to='sources.Source'),
        ),
    ]
