# Generated by Django 2.2 on 2020-09-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_auto_20190312_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='sources',
        ),
    ]
